# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0002_auto_20170621_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='folio',
        ),
        migrations.AddField(
            model_name='mascota',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='vacuna',
            field=models.ManyToManyField(blank=True, to='mascota.Vacuna'),
        ),
    ]
