# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0004_remove_mascota_vacuna'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='vacuna',
            field=models.ManyToManyField(blank=True, to='mascota.Vacuna'),
        ),
    ]
